apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: inventory-service-async-api
  description: Inventory Service Async API
  tags:
  - kafka
  links:
    - url: https://github.com/mmussett/eventcatalog-sample
      title: GitHub Repo 
      icon: github 
    - url: https://github.com/mmussett/eventcatalog-sample/blob/main/api-spec/asyncapi.yaml
      title: API Spec 
      icon: code
    - url: https://editor.swagger.io/?spec=https://github.com/mmussett/eventcatalog-sample/blob/main/api-spec/asyncapi.yaml
      title: Swagger Editor 
      icon: code
spec:
  type: asyncapi
  lifecycle: experimental
  owner: order-management
  system: order-management-system
  dependsOn: 
    - component: inventory-service
  dependencyOf:
    - component: inventory-service
  definition:
    $text: ./api-spec/asyncapi.yaml