apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: orders
  description: Everything related to order management
spec:
  owner: group:order-management
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: order-management
  description: 'The order management team is responsible for overseeing and optimizing the entire order lifecycle within our organization'
spec:
  type: department
  profile:
    displayName: 'The order management team'
    email: info@acme.com
  parent: 
  children: []