apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inventory-service
  title: Inventory Service
  description: Inventory Management Service
  tags:
    - flogo
    - kafka
    - eventcatalog
  links:
    - title: Repository
      description: GitHub repository
      url: https://github.com/mmussett/eventcatalog-sample
    - title: VSCode
      description: Edit in VSCode
      url: vscode://vscode.git/clone?url=https://github.com/mmussett/eventcatalog-sample
  annotations:
    github.com/project-slug: mmussett/mmussett/eventcatalog-sample
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  system: order-management-system
  owner: group:order-management
  consumesApis:
    - inventory-service-async-api
  providesApis:
    - inventory-service-async-api
  dependsOn:
    - component:kafka-broker