apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: eventcatalog-sample-locations
spec:
  targets:
    - ./groups.yaml
    - ./system.yaml
    - ./api-info.yaml
    - ./component-kafka-broker.yaml
    - ./component-channels.yaml
    - ./component-events.yaml
    - ./component-flogo-consumer.yaml
    - ./component-flogo-producer.yaml